# Generated by Django 4.2.7 on 2025-01-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaketUmroh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diskon', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tanggal_keberangkatan', models.CharField(max_length=100)),
                ('maskapai', models.CharField(max_length=100)),
                ('hotel_mekkah', models.CharField(max_length=255)),
                ('hotel_madinah', models.CharField(max_length=255)),
                ('gambar', models.ImageField(upload_to='paket_umroh/')),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
