# Generated by Django 4.2.7 on 2025-01-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umroh', '0002_landarrangement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landarrangement',
            name='gambar',
        ),
    ]
